source 'https://github.com/CocoaPods/Specs.git'

target 'JVFloatingDrawer' do
	pod "JVFloatingDrawer", :path => "../"
end

target 'JVFloatingDrawerTests' do
	pod "JVFloatingDrawer", :path => "../"
end

